language: python
branches: 
  only: 
  - master
install: 
- pip install pelican ghp-import
script: 
- make publish traveis_github
env: 
  global: 
    secure: FOEnMVj8oVkMFU3d5NuXbxt25ohCDf4LYBotzLuuQKTSbbqK/FbFeyOFm4ghvMGCcoDUGDw+uhvY6n9oQbELI2Gf9o+tnBdO1EHBfAC6/8x8mag7Tvj/ZOM1pGM/j0xaZrXA+rzjgcM/Ga8oJd32BXjemtmkfK8YabjinWI1u80=
